### ISSUE TITLE
chapter 10 rewrite

### ISSUE THREAD

**Issue by shiffman** [nature-of-code/noc-book-2023#44]
TBD

**Comment by hysysk** [comment]
In case you would refer to this paper in the renewed chapter, "imminent" should be "immanent".
https://github.com/nature-of-code/noc-book-2/blob/6fbfbd53c51ea7b984ebb7f72d28bf2c9c3a0126/content/10_nn.html#L50
https://dl.acm.org/doi/10.5555/65669.104377

**Comment by shiffman** [comment]
Thanks @hysysk the typo has now been corrected! Leaving this issue open to track Chapter 10.

**Comment by shiffman** [comment]
new chapter 10 is done!
